describe("apex-test-runner", function()
  local Helper

  before_each(function()
    Helper = require("tests.helpers.init")
    Helper.setup({ fn_overrides = { exepath = function(n) return n == "sf" and "/usr/bin/sf" or "" end } })
  end)

  after_each(function()
    Helper.teardown()
  end)

  describe("test result fixture shapes", function()
    it("test_success.json has expected summary shape", function()
      local json = Helper.load_fixture_text("apex-test-runner", "test_success.json")
      local ok, parsed = pcall(vim.json.decode, json)
      assert.is_true(ok, "fixture should be valid JSON")
      assert.are_equal(0, parsed.result.summary.failing)
      assert.are_equal("Passed", parsed.result.summary.outcome)
    end)
    it("test_with_failures.json has expected summary shape", function()
      local json = Helper.load_fixture_text("apex-test-runner", "test_with_failures.json")
      local ok, parsed = pcall(vim.json.decode, json)
      assert.is_true(ok)
      assert.are_equal(1, parsed.result.summary.failing)
      assert.are_equal("Failed", parsed.result.summary.outcome)
    end)
  end)

  describe("Const apex test arg builders", function()
    local Const

    before_each(function()
      Const = require("sf.const")
    end)

    it("get_apex_test_class_args builds full vector with coverage flag", function()
      local args = Const.get_apex_test_class_args("FakeTestClass", true)
      assert.are_equal("apex", args[1])
      assert.are_equal("run", args[2])
      assert.are_equal("test", args[3])
      assert.are_equal("-y", args[4])
      assert.are_equal("-n", args[5])
      assert.are_equal("FakeTestClass", args[6])
      assert.are_equal("--json", args[7])
      assert.are_equal("-c", args[8])
      assert.are_equal(8, #args)
    end)

    it("get_apex_test_class_args omits coverage flag when not requested", function()
      local args = Const.get_apex_test_class_args("FakeTestClass", false)
      assert.are_equal("FakeTestClass", args[6])
      assert.is_false(vim.tbl_contains(args, "-c"))
      assert.are_equal(7, #args)
    end)

    it("get_apex_test_method_args includes method name", function()
      local args = Const.get_apex_test_method_args("FakeTestClass.testMethod", false)
      assert.are_equal("apex", args[1])
      assert.are_equal("run", args[2])
      assert.are_equal("test", args[3])
      assert.are_equal("-y", args[4])
      assert.are_equal("-t", args[5])
      assert.are_equal("FakeTestClass.testMethod", args[6])
      assert.are_equal("--json", args[7])
      assert.are_equal(7, #args)
    end)

    it("get_apex_log_list_args appends target org", function()
      local args = Const.get_apex_log_list_args("test-user@example.com")
      assert.are_equal("apex", args[1])
      assert.are_equal("list", args[2])
      assert.are_equal("log", args[3])
      assert.are_equal("--json", args[4])
      assert.are_equal("-o", args[5])
      assert.are_equal("test-user@example.com", args[6])
      assert.are_equal(6, #args)
    end)

    it("get_apex_log_get_args includes log dir and id", function()
      local args = Const.get_apex_log_get_args("/logs", "07LFAKE000001234")
      assert.are_equal("apex", args[1])
      assert.are_equal("get", args[2])
      assert.are_equal("log", args[3])
      assert.are_equal("-d", args[4])
      assert.are_equal("/logs", args[5])
      assert.are_equal("-i", args[6])
      assert.are_equal("07LFAKE000001234", args[7])
      assert.are_equal(7, #args)
    end)
  end)

  describe("Coverage.enable/disable", function()
    local Coverage

    before_each(function()
      Coverage = require("sf.test.coverage")
    end)

    it("enable sets flag and shows coverage", function()
      vim.g.sf_coverage_enabled = false
      Coverage.enable()
      assert.is_true(vim.g.sf_coverage_enabled)
    end)

    it("disable clears flag and clears signs", function()
      vim.g.sf_coverage_enabled = true
      Coverage.disable()
      assert.is_false(vim.g.sf_coverage_enabled)
    end)
  end)
end)
