-- Smoke test: verify test infrastructure works.
-- Must be the first test to pass before any capability spec runs.

describe("smoke", function()
  it("tests run and assertions work", function()
    assert.is_true(true)
    assert.are_equal(1, 1)
    assert.is_not_equal(1, 2)
  end)

  it("test helpers module loads", function()
    local ok, helpers = pcall(require, "tests.helpers.init")
    assert.is_true(ok, "tests.helpers.init should load")
    assert.is_not_nil(helpers)
    assert.is_not_nil(helpers.mock_vim)
    assert.is_not_nil(helpers.mock_snacks)
    assert.is_not_nil(helpers.mock_notify)
    assert.is_not_nil(helpers.fixtures)
  end)

  it("mock_vim setup and restore cycles cleanly", function()
    local mock = require("tests.helpers.mock_vim")
    mock.setup({ system = true, notify = true })
    assert.is_not_nil(vim.system)
    -- vim.system should be our mock function
    local job = vim.system("sf", { "--version" }, { on_exit = function() end })
    assert.is_not_nil(job)
    assert.is_not_nil(job.start)
    assert.is_not_nil(job.result)
    mock.restore()
    -- After restore, vim.system is back to original
    assert.is_not_nil(vim.system)
  end)

  it("mock_snacks captures picker calls", function()
    local snacks = require("tests.helpers.mock_snacks")
    snacks.setup()
    Snacks.picker({ items = { { id = "1", text = "test" } }, confirm = function() end })
    local items = snacks.get_items()
    assert.is_not_nil(items)
    assert.are_equal(1, #items)
    assert.are_equal("1", items[1].id)
    snacks.restore()
  end)

  it("mock_notify captures messages", function()
    local notify = require("tests.helpers.mock_notify")
    notify.setup()
    vim.notify("hello world", vim.log.levels.INFO)
    local calls = notify.get_messages()
    assert.are_equal(1, #calls)
    assert.are_equal("hello world", calls[1])
    notify.restore()
  end)

  it("fixtures loader returns nil for nonexistent file", function()
    local f = require("tests.helpers.fixtures")
    local content, err = f.load_text("core-utilities", "nonexistent.json")
    assert.is_nil(content)
    assert.is_not_nil(err)
  end)
end)
