name: CI

on:
  pull_request:
    branches: [main, develop, feature/*, bug/*, release/*]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  stylua:
    name: stylua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --color always --check .

  luacheck:
    name: luacheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install luacheck
        run: |
          sudo apt-get update
          sudo apt-get install -y luarocks
          sudo luarocks install luacheck
      - name: lint
        run: make luacheck

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable
      - name: install vusted
        run: luarocks install vusted
      - name: run tests
        run: make test
        env:
          VUSTED_USE_LOCAL: 1
